name: DotNet Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - run: dotnet tool install -g GitVersion.Tool

      - name: GitVersion
        run: dotnet gitversion /l console /output buildserver

      - name: DotNet Build
        shell: pwsh
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet build --configuration Release --no-restore
          dotnet pack --configuration Release --no-restore 
      - name: DotNet Test
        shell: pwsh
        run: |
          dotnet test --no-build --no-restore
      - name: Push NuGet
        shell: pwsh
        run: dotnet nuget push **/*.nupkg --source $Env:SOURCE --api-key $Env:TOKEN --skip-duplicate
        env:
          SOURCE: 'https://api.nuget.org/v3/index.json'
          TOKEN: ${{ secrets.NUGET_API_KEY }}